name: 'auto-ci'
description: 'CI for monorepo based Node project'
inputs:
  configPath:
    description: 'path to config file'
    required: true
  modulesDir:
    description: 'the general directory which stores all modules'
    required: false
    default: ''

outputs:
  moduleDir: 
    description: 'root directory of the selected module'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'award'  
  color: 'green'
